name: Convert LaTeX to HTML with Sphinx

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

permissions:
  contents: write  # Grant write access to the GitHub Actions bot

jobs:
  sphinx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip pandoc pandoc-citeproc  # Install Pandoc and pandoc-citeproc
          pip3 install sphinx sphinx-wagtail-theme sphinxcontrib-bibtex restructuredtext-lint  # Install Sphinx, BibTeX extension, and linter

      - name: Verify Installed Packages
        run: pip3 list  # This will list all installed Python packages

      - name: Clean Build Directory
        run: rm -rf docs/build/html  # Clean previous builds

      - name: Create docs/source Directory
        run: mkdir -p docs/source  # Create a docs/source directory if it doesn't exist

      - name: Initialize Sphinx Documentation
        run: |
          cd docs
          sphinx-quickstart --quiet --sep --project="Handbook" --author="ARCTICS" --release="0.1" --language="en" --makefile

      - name: Check for LaTeX file
        run: ls -la  # List files to ensure main.tex exists

      - name: Convert LaTeX to RST with Bibliography
        run: |
          pandoc main.tex --bibliography=references.bib --filter pandoc-citeproc -o docs/source/main.rst  # Convert your LaTeX file to RST format with bibliography

      - name: Create Master Document (index.rst)
        run: |
          cat <<EOT > docs/source/index.rst
# Hello and Welcome!

We are a team of scientists and citizen scientists, all united by a shared passion for the aurora! Together, in the `Auroral Research Coordination: Towards Internationalised Citizen Science (ARCTICS) <https://collab.issibern.ch/arctics/>`_ group, we’ve combined our expertise to create two valuable resources for the aurora community.

Our Aurora Field Guide provides examples of various types of auroras, helping you recognize and identify different forms in your own photographs. Meanwhile, our Aurora Handbook delves deeper into aurora chasing, capturing images for scientific research, and contributing to our collective understanding. We explain the process of taking and submitting your photos, how collaborations between professional scientists and citizen scientists unfold, and highlight key discoveries that have emerged through this teamwork.

These guides are available to you free of charge, and we hope that you enjoy them! Happy aurora hunting from the ARCTICS team!

.. raw:: html

   <a href='https://zenodo.org/doi/10.5281/zenodo.13837258' style='display:inline-block; vertical-align:middle;'>
      <img src='https://zenodo.org/badge/862822419.svg' alt='DOI'>
   </a>

To cite the work, we ask that you use the above doi.

Both guides are licensed under a Creative Commons Attribution-NonCommercial 4.0 International License (CC BY-NC 4.0).

**Aurora Field Guide for Citizen Science**

.. image:: _static/Field_Guide_Cover.jpg
   :alt: Aurora Field Guide Cover
   :align: center

`Click Here for the Aurora Field Guide <_static/Aurora_Field_Guide.pdf>`_

**Aurora Handbook for Citizen Science**

.. image:: _static/Handbook_Cover.jpg
   :alt: Aurora Handbook Cover
   :align: center

.. toctree::
   :maxdepth: 2
   :caption: Contents:

   main
EOT
